import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, BellRing, BookOpen, ExternalLink, Pause, Play, Plus, Trash2 } from 'lucide-react';
import { api } from './api';
import { relativeTime } from './news-utils';
import EvaluationCenter from './EvaluationCenter';

const severityClass = { high: 'text-negative border-negative/25', medium: 'text-warning border-warning/25', low: 'text-cyan-300 border-cyan-400/25' };
const importanceLabel = { high: 'High', medium: 'Medium', low: 'Any' };
const ruleLabel = { change_above: 'Daily gain is above', change_below: 'Daily fall is more than', price_above: 'Price rises above', price_below: 'Price falls below', event: 'Important company news' };
const readerText = text => String(text ?? '')
    .replace('The latest persisted provider snapshot satisfies the configured threshold.', 'The latest available price meets the condition you selected.')
    .replace('Latest persisted price', 'Latest available price')
    .replace('Latest timestamped snapshot.', 'Latest available price information.');

export default function AlertsCenter() {
    const client = useQueryClient();
    const [kind, setKind] = useState('daily');
    const [ruleType, setRuleType] = useState('change_above');
    const rules = useQuery({ queryKey: ['alert-rules'], queryFn: api.alertRules });
    const alerts = useQuery({ queryKey: ['alerts'], queryFn: () => api.alerts(50) });
    const briefings = useQuery({ queryKey: ['briefings', kind], queryFn: () => api.briefings(kind) });
    const portfolio = useQuery({ queryKey: ['portfolio'], queryFn: api.portfolio });
    const refresh = () => { client.invalidateQueries({ queryKey: ['alert-rules'] }); client.invalidateQueries({ queryKey: ['alerts'] }); client.invalidateQueries({ queryKey: ['briefings'] }); };
    const create = useMutation({ mutationFn: api.createAlertRule, onSuccess: refresh });
    const update = useMutation({ mutationFn: ({ id, patch }) => api.updateAlertRule(id, patch), onSuccess: refresh });
    const remove = useMutation({ mutationFn: api.deleteAlertRule, onSuccess: refresh });
    const markRead = useMutation({ mutationFn: api.markAlertRead, onSuccess: () => client.invalidateQueries({ queryKey: ['alerts'] }) });
    const error = rules.error || alerts.error || briefings.error || create.error || update.error || remove.error;

    function submit(event) {
        event.preventDefault();
        const form = new FormData(event.currentTarget);
        const selectedRuleType = String(form.get('ruleType'));
        create.mutate({
            name: String(form.get('name')),
            symbol: String(form.get('symbol')),
            ruleType: selectedRuleType,
            threshold: selectedRuleType === 'event' ? undefined : Number(form.get('threshold')),
            minimumConfidence: Number(form.get('minimumConfidence')),
            minimumSeverity: String(form.get('minimumSeverity')),
            cooldownMinutes: Number(form.get('cooldownMinutes')),
            channels: { inApp: true, browser: form.get('browserPreference') === 'on', email: form.get('emailPreference') === 'on', telegram: form.get('telegramPreference') === 'on' },
            quietHours: { enabled: form.get('quietEnabled') === 'on', start: String(form.get('quietStart')), end: String(form.get('quietEnd')), timezone: 'Asia/Kolkata' },
            enabled: true
        });
    }

    return <div>
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-positive font-semibold">Stay informed</p><h1 className="text-3xl font-semibold mt-2">Alerts & briefings</h1><p className="text-sm text-slate-400 mt-2">Choose the price moves and company developments you want to follow.</p></div><div className="rounded-lg border border-positive/20 bg-positive/[.06] px-3 py-2 text-xs text-positive">App alerts are on</div></div>
        {error && <div role="alert" className="mt-5 rounded-xl border border-negative/30 bg-negative/10 p-4 text-sm text-negative">{error.message}</div>}
        <div className="grid xl:grid-cols-[.85fr_1.15fr] gap-5 mt-6">
            <section className="surface rounded-2xl p-5"><div className="flex items-center gap-2"><Plus size={16} className="text-positive"/><h2 className="font-semibold">Create an alert</h2></div><p className="text-xs text-slate-500 mt-1">Alerts are available for companies in your portfolio.</p><form onSubmit={submit} className="mt-5 grid sm:grid-cols-2 gap-3"><Input name="name" label="Alert name" placeholder="Large OLA move"/><Select name="symbol" label="Portfolio stock" options={(portfolio.data?.data ?? []).map(item => [item.nseSymbol || item.bseCode, item.nseSymbol || item.bseCode])}/><Select name="ruleType" label="Notify me when" value={ruleType} onChange={event => setRuleType(event.target.value)} options={[["change_above", "Daily gain is above"], ["change_below", "Daily fall is more than"], ["price_above", "Price rises above"], ["price_below", "Price falls below"], ["event", "There is important new company news"]]}/>{ruleType === 'event' ? <div className="rounded-xl border border-line p-3 text-xs text-slate-500">You will be alerted when an important company development is found.</div> : <Input name="threshold" label="Price or percentage" type="number" step="0.01" min="0.01" defaultValue="2"/>}<Select name="minimumSeverity" label="Importance" options={[["low", "Any"], ["medium", "Medium or high"], ["high", "High only"]]}/><Input name="minimumConfidence" label="Minimum confidence (%)" type="number" min="0" max="100" defaultValue="60"/><Input name="cooldownMinutes" label="Wait before repeating (minutes)" type="number" min="1" max="10080" defaultValue="60"/><div className="rounded-xl border border-line p-3"><label className="text-xs flex items-center gap-2"><input name="quietEnabled" type="checkbox" className="accent-emerald-400"/>Quiet hours</label><div className="flex gap-2 mt-2"><input aria-label="Quiet start" name="quietStart" type="time" defaultValue="22:00" className="min-w-0 w-full rounded-lg bg-white/[.03] border border-line p-2 text-xs"/><input aria-label="Quiet end" name="quietEnd" type="time" defaultValue="07:00" className="min-w-0 w-full rounded-lg bg-white/[.03] border border-line p-2 text-xs"/></div></div><div className="sm:col-span-2 rounded-xl border border-line bg-white/[.02] p-3"><p className="text-xs text-slate-500">Alerts currently appear inside STOCKER. You can save how you would like to receive them in the future.</p><div className="flex flex-wrap gap-4 mt-3 text-xs text-slate-400">{[['browserPreference', 'Browser'], ['emailPreference', 'Email'], ['telegramPreference', 'Telegram']].map(([name, label]) => <label key={name} className="flex items-center gap-2"><input name={name} type="checkbox" className="accent-emerald-400"/>{label}</label>)}</div></div><button disabled={create.isPending || !(portfolio.data?.data?.length)} className="sm:col-span-2 rounded-xl bg-positive text-ink py-3 text-sm font-semibold disabled:opacity-50">{create.isPending ? 'Creating…' : 'Create alert'}</button></form></section>
            <section className="surface rounded-2xl p-5"><div className="flex items-center gap-2"><BellRing size={16} className="text-positive"/><div><h2 className="font-semibold">Your alerts</h2><p className="text-xs text-slate-500 mt-1">Pause or delete an alert at any time.</p></div></div><div className="mt-4 divide-y divide-line">{(rules.data?.data ?? []).map(rule => <div key={rule.id} className="py-4 flex gap-3 items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 items-center"><p className="text-sm font-medium">{rule.name}</p><span className={`text-[10px] rounded-full border px-2 py-0.5 ${severityClass[rule.minimumSeverity]}`}>{importanceLabel[rule.minimumSeverity] ?? rule.minimumSeverity}</span>{!rule.enabled && <span className="text-[10px] text-slate-500">PAUSED</span>}</div><p className="text-xs text-slate-500 mt-1">{rule.symbol} · {ruleLabel[rule.ruleType] ?? 'Selected condition'}{rule.threshold ? ` · ${rule.threshold}` : ''} · {rule.minimumConfidence}% confidence or more</p><p className="text-[10px] text-slate-600 mt-2">Can repeat after {rule.cooldownMinutes} minutes{rule.quietHours?.enabled ? ` · quiet from ${rule.quietHours.start} to ${rule.quietHours.end} IST` : ''}</p></div><button aria-label={`${rule.enabled ? 'Pause' : 'Resume'} ${rule.name}`} onClick={() => update.mutate({ id: rule.id, patch: { enabled: !rule.enabled } })} className="rounded-lg border border-line p-2 text-slate-400">{rule.enabled ? <Pause size={15}/> : <Play size={15}/>}</button><button aria-label={`Delete ${rule.name}`} onClick={() => remove.mutate(rule.id)} className="rounded-lg border border-line p-2 text-slate-400 hover:text-negative"><Trash2 size={15}/></button></div>)}{!rules.data?.data?.length && <p className="py-10 text-center text-sm text-slate-500">You have not created any alerts yet.</p>}</div></section>
        </div>
        <section className="surface rounded-2xl p-5 mt-5"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-warning"/><div><h2 className="font-semibold">Alert history</h2><p className="text-xs text-slate-500 mt-1">{alerts.data?.meta?.unread ?? 0} unread</p></div></div><div className="grid lg:grid-cols-2 gap-3 mt-5">{(alerts.data?.data ?? []).map(item => <button key={item.id} onClick={() => !item.readAt && markRead.mutate(item.id)} className={`text-left rounded-xl border p-4 ${item.readAt ? 'border-line bg-white/[.015]' : 'border-positive/25 bg-positive/[.035]'}`}><div className="flex gap-2 items-center text-[10px]"><span className={severityClass[item.severity]?.split(' ')[0]}>{item.severity.toUpperCase()}</span><span className="text-slate-600">·</span><span className="text-slate-500">{relativeTime(item.triggeredAt)}</span></div><h3 className="text-sm font-medium mt-2">{item.title}</h3><p className="text-xs text-slate-400 leading-5 mt-2">{readerText(item.explanation)}</p><p className="text-[10px] text-slate-600 mt-3">{item.symbol} · {item.confidence}% confidence · information from {relativeTime(item.sourceAsOf)}</p><div className="mt-3 flex flex-wrap gap-2">{item.evidence?.map((evidence, index) => <a key={`${evidence.url}-${index}`} href={evidence.url || undefined} target="_blank" rel="noreferrer" onClick={event => event.stopPropagation()} className="text-[10px] text-cyan-300 flex items-center gap-1">{evidence.source}<ExternalLink size={10}/></a>)}</div></button>)}{!alerts.data?.data?.length && <p className="text-sm text-slate-500 lg:col-span-2 py-8 text-center">No alerts have been triggered yet.</p>}</div></section>
        <section className="surface rounded-2xl p-5 mt-5"><div className="flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex items-center gap-2"><BookOpen size={16} className="text-positive"/><div><h2 className="font-semibold">Portfolio briefing</h2><p className="text-xs text-slate-500 mt-1">A quick summary of recent changes in the companies you own.</p></div></div><select aria-label="Briefing kind" value={kind} onChange={event => setKind(event.target.value)} className="sm:ml-auto rounded-lg border border-line bg-ink px-3 py-2 text-xs"><option value="morning">Morning</option><option value="closing">Closing</option><option value="daily">Daily</option></select></div>{(briefings.data?.data ?? []).map(briefing => <div key={briefing.id} className="mt-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium">{briefing.title}</h3><p className="text-xs text-slate-500 mt-1">{briefing.summary}</p></div></div><div className="grid lg:grid-cols-2 gap-3 mt-4">{briefing.items.map(item => <div key={item.symbol} className="rounded-xl border border-line p-4"><p className="text-xs text-positive">{item.symbol} · {item.confidence}% confidence</p><h4 className="text-sm mt-2">{item.headline}</h4><p className="text-xs text-slate-500 leading-5 mt-2">{readerText(item.explanation)}</p></div>)}</div></div>)}</section>
        <div className="mt-10"><EvaluationCenter/></div>
    </div>;
}

function Input({ label, ...props }) { return <label className="text-xs text-slate-400"><span className="block mb-2">{label}</span><input {...props} required className="w-full rounded-xl border border-line bg-white/[.025] px-3 py-2.5 text-sm text-white"/></label>; }
function Select({ label, options, ...props }) { return <label className="text-xs text-slate-400"><span className="block mb-2">{label}</span><select {...props} required className="w-full rounded-xl border border-line bg-ink px-3 py-2.5 text-sm text-white">{options.length === 0 && <option value="">No portfolio stocks</option>}{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
