import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, BellRing, BriefcaseBusiness, ChevronRight, Command, Gauge, Layers3, LogOut, Moon, Newspaper, Plus, RefreshCw, Search, ShieldCheck, Sun, TrendingDown, TrendingUp, UserRound, X, Zap } from 'lucide-react';
import { api } from './api';
import { useAppStore } from './store';
import NewsExplorer from './NewsExplorer';
import MarketIntelligence from './MarketIntelligence';
import StockDetail from './StockDetail';
import AlertsCenter from './AlertsCenter';
import PortfolioPanel from './Portfolio';
import { relativeTime } from './news-utils';
const nav = [['Overview', Gauge, 'overview'], ['Market', Layers3, 'market'], ['Live news', Newspaper, 'news'], ['Portfolio', BriefcaseBusiness, 'portfolio'], ['Alerts', BellRing, 'alerts']];
const routeFromHash = () => nav.find(([, , route]) => route === window.location.hash.slice(2))?.[0] ?? 'Overview';
function App() {
    const { user, sessionReady, restoreSession, theme, toggleTheme } = useAppStore();
    useEffect(() => {
        const root = document.documentElement;
        root.classList.toggle('light', theme === 'light');
        root.classList.toggle('dark', theme === 'dark');
        root.dataset.theme = theme;
    }, [theme]);
    useEffect(() => { restoreSession(); }, [restoreSession]);
    if (!sessionReady)
        return <main className="grid-bg min-h-screen grid place-items-center"><div className="text-center"><Brand/><p className="mt-5 text-sm text-slate-500">Restoring secure session…</p></div></main>;
    if (!user)
        return <Auth toggleTheme={toggleTheme} theme={theme}/>;
    return <Dashboard toggleTheme={toggleTheme} theme={theme}/>;
}
function Auth({ toggleTheme, theme }) {
    const [mode, setMode] = useState('register');
    const [error, setError] = useState('');
    const { setSession } = useAppStore();
    const mutation = useMutation({ mutationFn: async (values) => mode === 'login' ? api.login(values.email, values.password) : api.register(values.email, values.password, values.name), onSuccess: r => setSession(r.accessToken, r.user), onError: e => setError(e.message) });
    function submit(e) { e.preventDefault(); setError(''); const f = new FormData(e.currentTarget); mutation.mutate({ email: String(f.get('email')), password: String(f.get('password')), name: String(f.get('name') ?? '') }); }
    return <main className="grid-bg min-h-screen lg:grid lg:grid-cols-[1.2fr_.8fr] relative"><button aria-label={`Switch to ${theme === 'dark' ? 'Financial Newspaper light' : 'Trading Terminal dark'} mode`} title={`Switch to ${theme === 'dark' ? 'Financial Newspaper light' : 'Trading Terminal dark'} mode`} onClick={toggleTheme} className="auth-theme-toggle theme-toggle fixed top-5 right-5 z-10 h-9 w-9 grid place-items-center border border-line rounded-lg text-slate-400">{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button>
 <section className="hidden lg:flex flex-col justify-between p-14 border-r border-line/70 relative overflow-hidden"><Brand /><div className="max-w-2xl"><div className="theme-accent-chip inline-flex items-center gap-2 rounded-full border border-positive/25 bg-positive/5 px-3 py-1.5 text-xs text-positive mb-7"><span className="theme-accent-dot w-1.5 h-1.5 rounded-full bg-positive pulse-dot"/>Facts before opinions</div><h1 className="text-6xl font-semibold leading-[1.05] tracking-[-.04em]">Indian markets,<br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-positive to-cyan-300">made explainable.</span></h1><p className="mt-7 text-lg text-slate-400 max-w-xl leading-8">Official announcements, trusted news and market context—brought together so you can understand what is happening.</p><div className="grid grid-cols-3 gap-3 mt-12"><Proof n="50" label="portfolio holdings"/><Proof n="100%" label="linked to sources"/><Proof n="0" label="trades placed"/></div></div><p className="text-xs text-slate-500 max-w-xl">STOCKER is an informational research tool. Its outlooks are estimates and are not financial advice.</p></section>
 <section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="lg:hidden mb-10"><Brand /></div><p className="theme-accent-text text-xs uppercase tracking-[.2em] text-positive font-semibold">Start with clarity</p><h2 className="text-3xl font-semibold mt-3">{mode === 'register' ? 'Create your workspace' : 'Welcome back'}</h2><p className="text-slate-400 mt-2">{mode === 'register' ? 'Track the companies you own and research.' : 'Continue your market research.'}</p><form className="mt-8 space-y-4" onSubmit={submit}>{mode === 'register' && <Field label="Your name" name="name" type="text" placeholder="Swayam"/>}<Field label="Email" name="email" type="email" placeholder="you@example.com"/><Field label="Password" name="password" type="password" placeholder="At least 12 characters"/>{error && <div role="alert" className="rounded-lg border border-negative/30 bg-negative/10 p-3 text-sm text-rose-300">{error}</div>}<label className="flex gap-3 text-xs text-slate-400 leading-5"><input required type="checkbox" className="mt-1 accent-emerald-400"/><span>I understand that STOCKER provides research information, not financial advice or guaranteed outcomes.</span></label><button disabled={mutation.isPending} className="w-full rounded-xl bg-positive text-ink font-semibold py-3 hover:bg-emerald-300 disabled:opacity-60">{mutation.isPending ? 'Please wait…' : mode === 'register' ? 'Create account' : 'Sign in'}</button></form><button className="w-full text-sm text-slate-400 mt-6 hover:text-white" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'register' ? 'Already have an account? Sign in' : 'New to STOCKER? Create an account'}</button><div className="mt-10 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={15}/>Your account and personal portfolio are protected</div></div></section>
    </main>;
}
function Brand() { return <div className="app-brand flex items-center gap-3"><div className="grid place-items-center h-9 w-9 rounded-xl bg-positive text-ink"><Activity size={20} strokeWidth={2.6}/></div><div><div className="font-bold tracking-[.18em]">STOCKER</div><div className="text-[9px] tracking-[.16em] text-slate-500 uppercase">market intelligence</div></div></div>; }
function Proof({ n, label }) { return <div className="surface rounded-xl p-4"><div className="font-mono text-xl text-white">{n}</div><div className="text-xs text-slate-500 mt-1">{label}</div></div>; }
function Field({ label, ...props }) { return <label className="block text-sm text-slate-300"><span className="block mb-2">{label}</span><input {...props} required className="w-full rounded-xl border border-line bg-[#0b1524] px-4 py-3 text-white placeholder:text-slate-600"/></label>; }
function Dashboard({ toggleTheme, theme }) {
    const [active, setActive] = useState(routeFromHash);
    const [search, setSearch] = useState(false);
    const [selectedStock, setSelectedStock] = useState('');
    const [refreshNotice, setRefreshNotice] = useState('');
    const { logout, user } = useAppStore();
    const client = useQueryClient();
    const overview = useQuery({ queryKey: ['overview'], queryFn: api.overview });
    const portfolio = useQuery({ queryKey: ['portfolio'], queryFn: api.portfolio });
    const news = useQuery({ queryKey: ['news'], queryFn: api.news });
    const health = useQuery({ queryKey: ['health'], queryFn: api.sourceHealth });
    const signals = useQuery({ queryKey: ['signals', 'RELIANCE'], queryFn: () => api.stockSignals('RELIANCE') });
    const alerts = useQuery({ queryKey: ['alerts'], queryFn: () => api.alerts(50) });
    const refreshAll = useMutation({
        mutationFn: api.refreshEverything,
        onSuccess: async response => {
            await client.invalidateQueries();
            setRefreshNotice(response?.data?.message || 'Everything is up to date.');
        },
        onError: error => setRefreshNotice(error.message || 'Refresh failed. Please try again.')
    });
    const healthItems = health.data?.data ?? [];
    const feedsHealthy = healthItems.length > 0 && healthItems.every(item => item.status === 'healthy');
    const navigate = (label) => { const route = nav.find(([name]) => name === label)?.[2] ?? 'overview'; window.location.hash = `#/${route}`; setActive(label); };
    useEffect(() => { const update = () => setActive(routeFromHash()); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
    useEffect(() => api.subscribe(({ data }) => { if (data?.event === 'news.created') { client.invalidateQueries({ queryKey: ['news'] }); client.invalidateQueries({ queryKey: ['news-explorer'] }); client.invalidateQueries({ queryKey: ['health'] }); } if (data?.event === 'analysis.completed') { client.invalidateQueries({ queryKey: ['signals'] }); client.invalidateQueries({ queryKey: ['news-analysis'] }); } if (data?.event === 'alert.created') { client.invalidateQueries({ queryKey: ['alerts'] }); } }), [client]);
    return <div className="stocker-shell min-h-screen w-full">
 <aside className="sidebar hidden lg:flex fixed inset-y-0 left-0 z-30 h-screen w-[228px] flex-col overflow-hidden border-r border-line/80 bg-[#091321]/90 p-4"><Brand /><nav className="mt-9 space-y-1">{nav.map(([label, Icon]) => <button key={label} onClick={() => navigate(label)} className={`w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active === label ? 'bg-positive/10 text-positive' : 'text-slate-400 hover:bg-white/5 hover:text-slate-200'}`}><Icon size={17}/>{label}</button>)}</nav><div className="mt-auto"><p className="px-3 pb-3 text-[10px] leading-4 text-slate-600">Alerts and daily market briefings are available for companies in your portfolio.</p><div className="border-t border-line pt-3 flex items-center gap-3 px-2"><div className="h-8 w-8 rounded-full bg-cyan-400/15 text-cyan-300 grid place-items-center"><UserRound size={15}/></div><div className="min-w-0"><p className="text-xs truncate">{user?.displayName || user?.email}</p><p className="text-[10px] text-slate-500">Personal workspace</p></div><button title="Sign out" onClick={logout} className="ml-auto text-slate-500 hover:text-white"><LogOut size={16}/></button></div></div>
 </aside>
 <div className="dashboard-content min-w-0 w-full"><header className="app-header h-16 border-b border-line/80 flex items-center px-4 sm:px-7 gap-4 sticky top-0 z-20 bg-ink/90 backdrop-blur-xl"><div className="lg:hidden"><Brand /></div><button onClick={() => setSearch(true)} className="header-search hidden sm:flex items-center gap-3 max-w-md flex-1 rounded-lg border border-line bg-white/[.025] px-3 py-2 text-sm text-slate-500"><Search size={16}/>Search stocks, news or ISIN…<span className="ml-auto flex items-center gap-1 text-[10px] border border-line rounded px-1.5"><Command size={10}/>K</span></button><div className="ml-auto flex items-center gap-2"><span className={`hidden md:flex items-center gap-2 text-[10px] uppercase tracking-wider mr-2 ${feedsHealthy ? 'text-positive' : 'text-warning'}`}><span className={`h-1.5 w-1.5 rounded-full ${feedsHealthy ? 'bg-positive pulse-dot' : 'bg-warning'}`}/>{feedsHealthy ? 'News up to date' : healthItems.length ? 'Some news delayed' : 'Waiting for news'}</span><button aria-label="Refresh everything" title="Refresh prices and reload all website data" disabled={refreshAll.isPending} onClick={() => { setRefreshNotice(''); refreshAll.mutate(); }} className="header-action h-9 sm:h-auto sm:min-h-9 px-2.5 sm:px-3 flex items-center gap-2 border border-line rounded-lg text-slate-400 hover:text-white disabled:opacity-50"><RefreshCw size={16} className={refreshAll.isPending ? 'animate-spin' : ''}/><span className="hidden sm:inline text-xs">{refreshAll.isPending ? 'Refreshing…' : 'Refresh'}</span></button><button aria-label={`Switch to ${theme === 'dark' ? 'Financial Newspaper light' : 'Trading Terminal dark'} mode`} title={`Switch to ${theme === 'dark' ? 'Financial Newspaper light' : 'Trading Terminal dark'} mode`} onClick={toggleTheme} className="theme-toggle h-9 w-9 grid place-items-center border border-line rounded-lg text-slate-400">{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button><button aria-label="Notifications" onClick={() => navigate('Alerts')} className="header-action h-9 w-9 grid place-items-center border border-line rounded-lg text-slate-400 relative"><Bell size={17}/>{(alerts.data?.meta?.unread ?? 0) > 0 && <span className="absolute -right-1 -top-1 min-w-4 h-4 rounded-full bg-negative text-white text-[9px] grid place-items-center px-1">{alerts.data.meta.unread}</span>}</button><button onClick={() => setSearch(true)} className="header-action sm:hidden h-9 w-9 grid place-items-center border border-line rounded-lg"><Search size={17}/></button></div></header>{refreshNotice && <div role="status" aria-live="polite" className={`mx-4 sm:mx-7 mt-3 rounded-lg border px-3 py-2 text-xs ${refreshAll.isError ? 'border-negative/30 bg-negative/10 text-negative' : 'border-positive/25 bg-positive/[.06] text-positive'}`}>{refreshNotice}</div>}
 <main className="dashboard-main w-full min-w-0 p-4 sm:p-7 max-w-[1600px] mx-auto">{active === 'Market' ? <MarketIntelligence onSelectStock={setSelectedStock}/> : active === 'Live news' ? <NewsExplorer /> : active === 'Alerts' ? <AlertsCenter /> : active === 'Portfolio' ? <><PageHeading title="Portfolio" subtitle="Track your holdings, profit or loss, company research and recent news."/><div className="mt-7"><PortfolioPanel data={portfolio.data?.data ?? []} summary={portfolio.data?.meta?.summary ?? {}} loading={portfolio.isLoading} onAdd={() => setSearch(true)} onSelect={setSelectedStock}/></div></> : <><section className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-xs text-slate-500">Indian market research workspace</p><h1 className="text-2xl sm:text-3xl font-semibold tracking-tight mt-1">Good evening, {user?.displayName?.split(' ')[0] || 'investor'}.</h1><p className="text-sm text-slate-400 mt-2">Here’s the latest view of your market.</p></div><div className="rounded-lg border border-warning/20 bg-warning/[.06] text-warning text-xs px-3 py-2 flex items-center gap-2"><AlertTriangle size={14}/>Prices may be delayed</div></section>
 <div className="grid xl:grid-cols-[1fr_340px] gap-5 mt-7"><div className="space-y-5"><IndexPanel data={overview.data?.data} onOpen={() => navigate('Market')}/><PortfolioPanel data={portfolio.data?.data ?? []} summary={portfolio.data?.meta?.summary ?? {}} loading={portfolio.isLoading} onAdd={() => setSearch(true)} onSelect={setSelectedStock}/><NewsPanel data={news.data?.data ?? []} onOpen={() => navigate('Live news')}/></div><div className="space-y-5"><Mood data={overview.data?.data?.mood}/><SignalCard data={signals.data?.data?.[0]}/><SourceHealth data={health.data?.data ?? []}/></div></div></>}
 </main></div>{search && <SearchDialog onClose={() => setSearch(false)}/>} {selectedStock && <StockDetail symbol={selectedStock} onClose={() => setSelectedStock('')}/>}<div className="lg:hidden fixed bottom-0 left-0 right-0 z-30 border-t border-line bg-ink/95 backdrop-blur p-2 flex justify-around">{nav.map(([label, Icon]) => <button key={label} onClick={() => navigate(label)} className={`p-2 ${active === label ? 'text-positive' : 'text-slate-500'}`} aria-label={label}><Icon size={20}/></button>)}</div>
    </div>;
}
function PageHeading({ title, subtitle }) { return <section><h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">{title}</h1><p className="text-sm text-slate-400 mt-2">{subtitle}</p></section>; }
function IndexPanel({ data, onOpen }) { const indices = data?.indices ?? []; const breadth = data?.breadth ?? {}; const sectors = data?.sectors ?? []; return <section className="surface rounded-2xl p-5 shadow-glow"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Market overview</h2><p className="text-xs text-slate-500 mt-1">Latest available market prices</p></div><button onClick={onOpen} className="text-xs text-slate-400 flex items-center">View market <ChevronRight size={14}/></button></div><div className="grid md:grid-cols-2 gap-3 mt-5">{indices.map((x) => <div key={x.symbol} className="rounded-xl bg-white/[.025] border border-line/70 p-4"><div className="text-xs text-slate-500">{x.symbol === 'NIFTY50' ? 'NIFTY 50' : x.symbol}</div><div className="flex items-end justify-between mt-1"><span className="text-xl font-mono">{Number(x.value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span><Change value={x.changePercent}/></div><p className="text-[10px] text-slate-600 mt-2">{x.source} · {x.asOf ? relativeTime(x.asOf) : 'time unavailable'}</p></div>)}{!indices.length && sectors.slice(0, 4).map(sector => <div key={sector.sector} className="rounded-xl bg-white/[.025] border border-line/70 p-4"><p className="text-xs text-slate-500">{sector.sector}</p><div className="flex items-end justify-between mt-2"><span className="text-sm">{sector.companyCount} companies</span><Change value={sector.averageChangePercent}/></div></div>)}</div><div className="grid grid-cols-3 border-t border-line mt-5 pt-4 text-center"><Metric label="Advances" value={breadth.advances ?? 0} good/><Metric label="Declines" value={breadth.declines ?? 0}/><Metric label="Unchanged" value={breadth.unchanged ?? 0}/></div></section>; }
function Metric({ label, value, good }) { return <div><div className={`font-mono ${good ? 'text-positive' : ''}`}>{value}</div><div className="text-[10px] uppercase tracking-wider text-slate-500 mt-1">{label}</div></div>; }
function Change({ value }) { const good = value >= 0; return <span className={`text-xs font-mono flex items-center ${good ? 'text-positive' : 'text-negative'}`}>{good ? <ArrowUpRight size={13}/> : <ArrowDownRight size={13}/>} {Math.abs(value).toFixed(2)}%</span>; }
export function SignalPill({ label }) { const pos = label.includes('Positive') || label.includes('positive'), neg = label.includes('Negative') || label.includes('negative'); return <span className={`inline-flex gap-1.5 items-center text-[11px] rounded-full px-2 py-1 ${pos ? 'bg-positive/10 text-positive' : neg ? 'bg-negative/10 text-negative' : 'bg-slate-500/10 text-slate-400'}`}>{pos ? <TrendingUp size={12}/> : neg ? <TrendingDown size={12}/> : <Activity size={12}/>} {label}</span>; }
function NewsPanel({ data, onOpen }) { return <section className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Latest news</h2><p className="text-xs text-slate-500 mt-1">Recent stories from trusted publishers</p></div><button onClick={onOpen} className="text-xs text-positive">View all news</button></div><div className="mt-5">{data.slice(0, 5).map((n) => <article key={n.id} className="relative pl-7 pb-6 last:pb-0 border-l border-line ml-2"><span className="absolute -left-1.5 top-1 h-3 w-3 rounded-full bg-positive border-[3px] border-panel"/><div className="flex flex-wrap gap-2 items-center text-[10px] text-slate-500"><span className="text-positive">{relativeTime(n.publishedAt)}</span><span>·</span><span>{n.sourceName}</span>{n.official && <span className="border border-positive/30 text-positive rounded px-1.5">OFFICIAL</span>}</div><h3 className="text-sm font-medium mt-2">{n.title}</h3><div className="flex items-center gap-2 mt-3">{n.symbols?.map(symbol => <span key={symbol} className="text-[10px] rounded bg-cyan-400/10 text-cyan-300 px-2 py-1">{symbol}</span>)}{n.duplicateCount > 1 && <span className="text-[10px] text-slate-500">Covered by {n.duplicateCount} sources</span>}</div></article>)}{!data.length && <p className="text-sm text-slate-500">No news is available yet. Please check again shortly.</p>}</div></section>; }
function Mood({ data }) { return <section className="surface rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-slate-500">Overall market mood</p><h2 className="text-lg font-semibold mt-2">{data?.label ?? 'Cautiously positive'}</h2></div><div className="h-14 w-14 rounded-full border-4 border-positive/20 border-t-positive grid place-items-center font-mono text-sm">{data?.score ?? 62}</div></div><p className="text-xs leading-5 text-slate-400 mt-4">{data?.explanation ?? 'Breadth is positive, while mixed global cues keep conviction moderate.'}</p><div className="mt-4 h-1.5 rounded-full bg-negative/30 overflow-hidden"><div className="h-full w-[62%] bg-gradient-to-r from-warning to-positive rounded-full"/></div><div className="flex justify-between text-[9px] text-slate-600 mt-1"><span>Risk-off</span><span>Balanced</span><span>Risk-on</span></div></section>; }
function SignalCard({ data }) { const signal = data ?? { symbol: 'RELIANCE', label: 'Not enough information', confidence: 0, reasons: ['We need more recent information before showing an outlook.'], risks: [] }; return <section className="surface rounded-2xl p-5 border-positive/20"><div className="flex items-center gap-2 text-positive"><Zap size={16}/><p className="text-[10px] uppercase tracking-[.16em] font-semibold">Stock outlook</p></div><div className="flex items-center justify-between mt-4"><div><h3 className="font-semibold">{signal.symbol || 'RELIANCE'}</h3><SignalPill label={signal.label}/></div><div className="text-right"><div className="font-mono text-lg">{signal.confidence}%</div><div className="text-[10px] text-slate-500">confidence</div></div></div><div className="mt-4 border-t border-line pt-4"><h4 className="text-xs font-semibold">Why this outlook?</h4><ul className="mt-2 space-y-2 text-xs text-slate-400">{signal.reasons?.slice(0, 3).map(reason => <li key={reason} className="flex gap-2"><span className="text-positive">+</span>{reason}</li>)}{signal.risks?.slice(0, 2).map(risk => <li key={risk} className="flex gap-2"><span className="text-warning">!</span>{risk}</li>)}</ul></div><p className="mt-3 text-[9px] text-slate-600 leading-4">For information only. This is not financial advice. Read the linked news before making a decision.</p></section>; }
function SourceHealth({ data }) { const healthyCount = data.filter(item => item.status === 'healthy').length; const total = data.length; const allHealthy = total > 0 && healthyCount === total; return <section className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">News sources</h2><span className={`text-[10px] flex gap-1.5 items-center ${allHealthy ? 'text-positive' : 'text-warning'}`}><span className={`h-1.5 w-1.5 rounded-full ${allHealthy ? 'bg-positive' : 'bg-warning'}`}/>{allHealthy ? 'Up to date' : total ? 'Some delayed' : 'Checking'}</span></div>{total ? <div className="mt-4 rounded-lg border border-line p-3 flex items-center gap-3"><div className="h-8 w-8 rounded-lg bg-positive/10 text-positive grid place-items-center"><ShieldCheck size={16}/></div><div className="min-w-0"><p className="text-xs">{healthyCount} of {total} sources available</p><p className="text-[10px] text-slate-500">News is collected from established publishers</p></div></div> : <p className="mt-4 text-xs leading-5 text-slate-500">News sources are being checked. Please check again shortly.</p>}</section>; }
function SearchDialog({ onClose }) {
    const [q, setQ] = useState('');
    const [selected, setSelected] = useState(null);
    const client = useQueryClient();
    const results = useQuery({ queryKey: ['search', q], queryFn: () => api.search(q), enabled: q.length > 0 && !selected });
    const add = useMutation({
        mutationFn: ({ symbol, quantity, averageBuyPrice }) => api.addPortfolio(symbol, quantity, averageBuyPrice),
        onSuccess: () => {
            client.invalidateQueries({ queryKey: ['portfolio'] });
            client.invalidateQueries({ queryKey: ['portfolio-news'] });
            onClose();
        }
    });
    function submit(event) {
        event.preventDefault();
        const form = new FormData(event.currentTarget);
        add.mutate({ symbol: selected.nseSymbol || selected.bseCode, quantity: Number(form.get('quantity')), averageBuyPrice: Number(form.get('averageBuyPrice')) });
    }
    return <div className="fixed inset-0 z-50 bg-black/65 backdrop-blur-sm p-4 sm:p-20" onMouseDown={event => event.target === event.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-label="Add portfolio holding" className="surface max-w-2xl mx-auto rounded-2xl shadow-2xl overflow-hidden"><div className="flex items-center gap-3 p-4 border-b border-line"><Search size={20} className="text-positive"/><input autoFocus={!selected} value={q} onChange={event => { setQ(event.target.value); setSelected(null); }} placeholder="Company, NSE symbol, BSE code or ISIN" className="bg-transparent flex-1 outline-none text-sm"/><button onClick={onClose} className="text-slate-500" aria-label="Close"><X size={18}/></button></div><div className="p-3 min-h-48 max-h-[60vh] overflow-y-auto scrollbar">{selected ? <form onSubmit={submit} className="p-3"><button type="button" onClick={() => setSelected(null)} className="text-xs text-slate-500 hover:text-white">← Choose a different stock</button><div className="mt-4 rounded-xl border border-line p-4"><p className="font-medium">{selected.companyName}</p><p className="text-xs text-slate-500 mt-1">{selected.nseSymbol || selected.bseCode}</p></div><div className="grid sm:grid-cols-2 gap-3 mt-4"><Field label="Quantity" name="quantity" type="number" min="0.0001" step="0.0001" placeholder="10"/><Field label="Average buy price (₹)" name="averageBuyPrice" type="number" min="0.01" step="0.01" placeholder="125.50"/></div><button disabled={add.isPending} className="w-full mt-4 rounded-xl bg-positive py-3 text-sm font-semibold text-ink disabled:opacity-50">{add.isPending ? 'Adding…' : 'Add to portfolio'}</button></form> : <>{!q && <div className="py-14 text-center"><Search className="mx-auto text-slate-600"/><p className="text-sm text-slate-400 mt-3">Search NSE and BSE listed companies</p><p className="text-xs text-slate-600 mt-1">Try OLAELEC, RELIANCE, 544225 or an ISIN</p></div>}{results.data?.data?.map(stock => { const symbol = stock.nseSymbol || stock.bseCode; return <button onClick={() => setSelected(stock)} key={stock.id} className="w-full flex items-center gap-3 rounded-xl p-3 hover:bg-white/[.04] text-left"><div className="h-9 w-9 rounded-lg bg-cyan-400/10 text-cyan-300 grid place-items-center text-xs font-semibold">{symbol.slice(0, 2)}</div><div className="min-w-0"><div className="text-sm font-medium">{stock.companyName}</div><div className="text-[11px] text-slate-500">NSE: {stock.nseSymbol || '—'} · BSE: {stock.bseCode || '—'} · {stock.sector}</div></div><Plus size={16} className="ml-auto text-positive"/></button>; })}{results.isFetching && <p className="text-center text-xs text-slate-500 py-8">Searching…</p>}</>}{add.error && <p role="alert" className="m-3 p-3 rounded-lg bg-negative/10 text-negative text-xs">{add.error.message}</p>}</div><div className="border-t border-line px-4 py-3 text-[10px] text-slate-600"><span>Maximum 50 portfolio holdings</span></div></div></div>;
}
export default App;
