import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, BellOff, BellRing, ChevronRight, Command, Eye, FileText, Gauge, LogOut, Moon, Newspaper, Pause, Plus, Search, ShieldCheck, Sun, Trash2, TrendingDown, TrendingUp, UserRound, X, Zap } from 'lucide-react';
import { api } from './api';
import { useAppStore } from './store';
import NewsExplorer from './NewsExplorer';
import { relativeTime } from './news-utils';
const chart = [{ t: '09:15', v: 24760 }, { t: '10:00', v: 24810 }, { t: '11:00', v: 24784 }, { t: '12:00', v: 24866 }, { t: '13:00', v: 24842 }, { t: '14:00', v: 24914 }, { t: '15:30', v: 24894 }];
const nav = [['Overview', Gauge, 'overview'], ['Live news', Newspaper, 'news'], ['Watchlist', Eye, 'watchlist']];
const routeFromHash = () => nav.find(([, , route]) => route === window.location.hash.slice(2))?.[0] ?? 'Overview';
function App() {
    const { user, sessionReady, restoreSession, theme, toggleTheme } = useAppStore();
    useEffect(() => { document.documentElement.classList.toggle('light', theme === 'light'); }, [theme]);
    useEffect(() => { restoreSession(); }, [restoreSession]);
    if (!sessionReady)
        return <main className="grid-bg min-h-screen grid place-items-center"><div className="text-center"><Brand/><p className="mt-5 text-sm text-slate-500">Restoring secure session…</p></div></main>;
    if (!user)
        return <Auth />;
    return <Dashboard toggleTheme={toggleTheme} theme={theme}/>;
}
function Auth() {
    const [mode, setMode] = useState('register');
    const [error, setError] = useState('');
    const { setSession } = useAppStore();
    const mutation = useMutation({ mutationFn: async (values) => mode === 'login' ? api.login(values.email, values.password) : api.register(values.email, values.password, values.name), onSuccess: r => setSession(r.accessToken, r.user), onError: e => setError(e.message) });
    function submit(e) { e.preventDefault(); setError(''); const f = new FormData(e.currentTarget); mutation.mutate({ email: String(f.get('email')), password: String(f.get('password')), name: String(f.get('name') ?? '') }); }
    return <main className="grid-bg min-h-screen lg:grid lg:grid-cols-[1.2fr_.8fr]">
 <section className="hidden lg:flex flex-col justify-between p-14 border-r border-line/70 relative overflow-hidden"><Brand /><div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full border border-positive/25 bg-positive/5 px-3 py-1.5 text-xs text-positive mb-7"><span className="w-1.5 h-1.5 rounded-full bg-positive pulse-dot"/>Evidence before opinion</div><h1 className="text-6xl font-semibold leading-[1.05] tracking-[-.04em]">Indian markets,<br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-positive to-cyan-300">made explainable.</span></h1><p className="mt-7 text-lg text-slate-400 max-w-xl leading-8">Official announcements, attributed news and market context—joined into signals you can inspect, challenge and understand.</p><div className="grid grid-cols-3 gap-3 mt-12"><Proof n="10" label="stock watchlist"/><Proof n="100%" label="source-linked"/><Proof n="0" label="trades placed"/></div></div><p className="text-xs text-slate-500 max-w-xl">STOCKER is an informational research tool. Signals are probabilistic and are not financial advice.</p></section>
 <section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="lg:hidden mb-10"><Brand /></div><p className="text-xs uppercase tracking-[.2em] text-positive font-semibold">Start with clarity</p><h2 className="text-3xl font-semibold mt-3">{mode === 'register' ? 'Create your workspace' : 'Welcome back'}</h2><p className="text-slate-400 mt-2">{mode === 'register' ? 'Monitor the companies that matter to you.' : 'Continue your market research.'}</p><form className="mt-8 space-y-4" onSubmit={submit}>{mode === 'register' && <Field label="Your name" name="name" type="text" placeholder="Swayam"/>}<Field label="Email" name="email" type="email" placeholder="you@example.com"/><Field label="Password" name="password" type="password" placeholder="At least 12 characters"/>{error && <div role="alert" className="rounded-lg border border-negative/30 bg-negative/10 p-3 text-sm text-rose-300">{error}</div>}<label className="flex gap-3 text-xs text-slate-400 leading-5"><input required type="checkbox" className="mt-1 accent-emerald-400"/><span>I understand that STOCKER provides research information, not financial advice or guaranteed outcomes.</span></label><button disabled={mutation.isPending} className="w-full rounded-xl bg-positive text-ink font-semibold py-3 hover:bg-emerald-300 disabled:opacity-60">{mutation.isPending ? 'Please wait…' : mode === 'register' ? 'Create account' : 'Sign in'}</button></form><button className="w-full text-sm text-slate-400 mt-6 hover:text-white" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'register' ? 'Already have an account? Sign in' : 'New to STOCKER? Create an account'}</button><div className="mt-10 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={15}/>Short-lived access tokens · rotated refresh sessions</div></div></section>
    </main>;
}
function Brand() { return <div className="flex items-center gap-3"><div className="grid place-items-center h-9 w-9 rounded-xl bg-positive text-ink"><Activity size={20} strokeWidth={2.6}/></div><div><div className="font-bold tracking-[.18em]">STOCKER</div><div className="text-[9px] tracking-[.16em] text-slate-500 uppercase">market intelligence</div></div></div>; }
function Proof({ n, label }) { return <div className="surface rounded-xl p-4"><div className="font-mono text-xl text-white">{n}</div><div className="text-xs text-slate-500 mt-1">{label}</div></div>; }
function Field({ label, ...props }) { return <label className="block text-sm text-slate-300"><span className="block mb-2">{label}</span><input {...props} required className="w-full rounded-xl border border-line bg-[#0b1524] px-4 py-3 text-white placeholder:text-slate-600"/></label>; }
function Dashboard({ toggleTheme, theme }) {
    const [active, setActive] = useState(routeFromHash);
    const [search, setSearch] = useState(false);
    const { logout, user } = useAppStore();
    const client = useQueryClient();
    const overview = useQuery({ queryKey: ['overview'], queryFn: api.overview });
    const watchlist = useQuery({ queryKey: ['watchlist'], queryFn: api.watchlist });
    const news = useQuery({ queryKey: ['news'], queryFn: api.news });
    const health = useQuery({ queryKey: ['health'], queryFn: api.sourceHealth });
    const healthItems = health.data?.data ?? [];
    const feedsHealthy = healthItems.length > 0 && healthItems.every(item => item.status === 'healthy');
    const navigate = (label) => { const route = nav.find(([name]) => name === label)?.[2] ?? 'overview'; window.location.hash = `#/${route}`; setActive(label); };
    useEffect(() => { const update = () => setActive(routeFromHash()); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
    useEffect(() => api.subscribe(({ data }) => { if (data?.event === 'news.created') { client.invalidateQueries({ queryKey: ['news'] }); client.invalidateQueries({ queryKey: ['news-explorer'] }); client.invalidateQueries({ queryKey: ['health'] }); } }), [client]);
    return <div className="min-h-screen lg:grid lg:grid-cols-[228px_1fr]">
 <aside className="sidebar hidden lg:flex sticky top-0 h-screen flex-col border-r border-line/80 bg-[#091321]/90 p-4"><Brand /><nav className="mt-9 space-y-1">{nav.map(([label, Icon]) => <button key={label} onClick={() => navigate(label)} className={`w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active === label ? 'bg-positive/10 text-positive' : 'text-slate-400 hover:bg-white/5 hover:text-slate-200'}`}><Icon size={17}/>{label}</button>)}</nav><div className="mt-auto"><p className="px-3 pb-3 text-[10px] leading-4 text-slate-600">Alerts, briefings, portfolio and performance arrive in later phases.</p><div className="border-t border-line pt-3 flex items-center gap-3 px-2"><div className="h-8 w-8 rounded-full bg-cyan-400/15 text-cyan-300 grid place-items-center"><UserRound size={15}/></div><div className="min-w-0"><p className="text-xs truncate">{user?.displayName || user?.email}</p><p className="text-[10px] text-slate-500">Personal workspace</p></div><button title="Sign out" onClick={logout} className="ml-auto text-slate-500 hover:text-white"><LogOut size={16}/></button></div></div>
 </aside>
 <div className="min-w-0"><header className="h-16 border-b border-line/80 flex items-center px-4 sm:px-7 gap-4 sticky top-0 z-20 bg-ink/90 backdrop-blur-xl"><div className="lg:hidden"><Brand /></div><button onClick={() => setSearch(true)} className="hidden sm:flex items-center gap-3 max-w-md flex-1 rounded-lg border border-line bg-white/[.025] px-3 py-2 text-sm text-slate-500"><Search size={16}/>Search stocks, news or ISIN…<span className="ml-auto flex items-center gap-1 text-[10px] border border-line rounded px-1.5"><Command size={10}/>K</span></button><div className="ml-auto flex items-center gap-2"><span className={`hidden md:flex items-center gap-2 text-[10px] uppercase tracking-wider mr-2 ${feedsHealthy ? 'text-positive' : 'text-warning'}`}><span className={`h-1.5 w-1.5 rounded-full ${feedsHealthy ? 'bg-positive pulse-dot' : 'bg-warning'}`}/>{feedsHealthy ? 'Feeds healthy' : healthItems.length ? 'Feed degraded' : 'Feed awaiting worker'}</span><button aria-label="Change theme" onClick={toggleTheme} className="h-9 w-9 grid place-items-center border border-line rounded-lg text-slate-400">{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button><button aria-label="Notifications" className="h-9 w-9 grid place-items-center border border-line rounded-lg text-slate-400 relative"><Bell size={17}/></button><button onClick={() => setSearch(true)} className="sm:hidden h-9 w-9 grid place-items-center border border-line rounded-lg"><Search size={17}/></button></div></header>
 <main className="p-4 sm:p-7 max-w-[1600px] mx-auto">{active === 'Live news' ? <NewsExplorer /> : active === 'Watchlist' ? <><PageHeading title="Watchlist" subtitle="Manage monitored companies and alert delivery."/><div className="mt-7"><WatchlistPanel data={watchlist.data?.data ?? []} loading={watchlist.isLoading} onAdd={() => setSearch(true)}/></div></> : <><section className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-xs text-slate-500">Indian market research workspace</p><h1 className="text-2xl sm:text-3xl font-semibold tracking-tight mt-1">Good evening, {user?.displayName?.split(' ')[0] || 'investor'}.</h1><p className="text-sm text-slate-400 mt-2">Here’s the evidence-backed view of your market.</p></div><div className="rounded-lg border border-warning/20 bg-warning/[.06] text-warning text-xs px-3 py-2 flex items-center gap-2"><AlertTriangle size={14}/>Delayed demonstration data</div></section>
 <div className="grid xl:grid-cols-[1fr_340px] gap-5 mt-7"><div className="space-y-5"><IndexPanel data={overview.data?.data}/><WatchlistPanel data={watchlist.data?.data ?? []} loading={watchlist.isLoading} onAdd={() => setSearch(true)}/><NewsPanel data={news.data?.data ?? []} onOpen={() => navigate('Live news')}/></div><div className="space-y-5"><Mood data={overview.data?.data?.mood}/><SignalCard /><SourceHealth data={health.data?.data ?? []}/></div></div></>}
 </main></div>{search && <SearchDialog onClose={() => setSearch(false)}/>}<div className="lg:hidden fixed bottom-0 left-0 right-0 z-30 border-t border-line bg-ink/95 backdrop-blur p-2 flex justify-around">{nav.map(([label, Icon]) => <button key={label} onClick={() => navigate(label)} className={`p-2 ${active === label ? 'text-positive' : 'text-slate-500'}`} aria-label={label}><Icon size={20}/></button>)}</div>
    </div>;
}
function PageHeading({ title, subtitle }) { return <section><h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">{title}</h1><p className="text-sm text-slate-400 mt-2">{subtitle}</p></section>; }
function IndexPanel({ data }) { const indices = data?.indices ?? [{ symbol: 'NIFTY50', value: 24894.25, changePercent: .64 }, { symbol: 'SENSEX', value: 81207.40, changePercent: .58 }]; return <section className="surface rounded-2xl p-5 shadow-glow"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Market overview</h2><p className="text-xs text-slate-500 mt-1">As of 15:30 IST · delayed</p></div><button className="text-xs text-slate-400 flex items-center">View market <ChevronRight size={14}/></button></div><div className="grid md:grid-cols-[220px_1fr] gap-6 mt-5"><div className="space-y-3">{indices.map((x) => <div key={x.symbol} className="rounded-xl bg-white/[.025] border border-line/70 p-4"><div className="text-xs text-slate-500">{x.symbol === 'NIFTY50' ? 'NIFTY 50' : x.symbol}</div><div className="flex items-end justify-between mt-1"><span className="text-xl font-mono">{Number(x.value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</span><Change value={x.changePercent}/></div></div>)}</div><div className="h-48"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#35d399" stopOpacity={.26}/><stop offset="1" stopColor="#35d399" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1e2c40" vertical={false}/><XAxis dataKey="t" tick={{ fill: '#64748b', fontSize: 10 }} axisLine={false} tickLine={false}/><YAxis hide domain={['dataMin-20', 'dataMax+20']}/><Tooltip contentStyle={{ background: '#0e1929', border: '1px solid #213047', borderRadius: 10 }}/><Area type="monotone" dataKey="v" stroke="#35d399" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="grid grid-cols-3 border-t border-line mt-5 pt-4 text-center"><Metric label="Advances" value="1,378" good/><Metric label="Declines" value="982"/><Metric label="Unchanged" value="126"/></div></section>; }
function Metric({ label, value, good }) { return <div><div className={`font-mono ${good ? 'text-positive' : ''}`}>{value}</div><div className="text-[10px] uppercase tracking-wider text-slate-500 mt-1">{label}</div></div>; }
function Change({ value }) { const good = value >= 0; return <span className={`text-xs font-mono flex items-center ${good ? 'text-positive' : 'text-negative'}`}>{good ? <ArrowUpRight size={13}/> : <ArrowDownRight size={13}/>} {Math.abs(value).toFixed(2)}%</span>; }
function WatchlistBase({ data, loading, onAdd }) { return <section className="surface rounded-2xl overflow-hidden"><div className="p-5 flex items-center justify-between"><div><h2 className="font-semibold">Your watchlist</h2><p className="text-xs text-slate-500 mt-1">{data.length} of 10 companies monitored</p></div><button onClick={onAdd} className="flex gap-2 items-center text-xs rounded-lg bg-positive text-ink font-semibold px-3 py-2"><Plus size={14}/>Add stock</button></div>{loading ? <div className="p-5 animate-pulse text-sm text-slate-500">Loading watchlist…</div> : data.length === 0 ? <div className="border-t border-line py-12 text-center"><Eye className="mx-auto text-slate-600"/><p className="mt-3 text-sm">Your watchlist is empty</p><p className="text-xs text-slate-500 mt-1">Add up to 10 NSE/BSE companies to begin.</p></div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500 border-y border-line"><tr><th className="text-left font-medium p-3 pl-5">Company</th><th className="text-right font-medium p-3">Price</th><th className="text-right font-medium p-3">Day</th><th className="text-left font-medium p-3">Signal</th><th className="text-right font-medium p-3 pr-5">Freshness</th></tr></thead><tbody>{data.map(s => <tr key={s.id} className="border-b border-line/60 last:border-0 hover:bg-white/[.02]"><td className="p-3 pl-5"><div className="font-medium">{s.nseSymbol}</div><div className="text-[11px] text-slate-500 max-w-48 truncate">{s.companyName}</div></td><td className="p-3 text-right font-mono">₹{s.price.toLocaleString('en-IN')}</td><td className="p-3"><div className="flex justify-end"><Change value={s.changePercent}/></div></td><td className="p-3"><SignalPill label={s.signal}/></td><td className="p-3 pr-5 text-right text-[11px] text-slate-500">15m · {s.source}</td></tr>)}</tbody></table></div>}</section>; }
export function WatchlistPanel({ data, loading, onAdd }) {
    const client = useQueryClient();
    const remove = useMutation({ mutationFn: (symbol) => api.removeWatchlist(symbol), onSuccess: () => client.invalidateQueries({ queryKey: ['watchlist'] }) });
    const pause = useMutation({ mutationFn: ({ symbol, paused }) => api.pauseWatchlist(symbol, paused), onSuccess: () => client.invalidateQueries({ queryKey: ['watchlist'] }) });
    const error = remove.error || pause.error;
    return <div className="space-y-3"><WatchlistBase data={data} loading={loading} onAdd={onAdd}/>{data.length > 0 && <section className="surface rounded-2xl p-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Watchlist controls</h3>{error && <p role="alert" className="mt-3 rounded-lg bg-negative/10 p-3 text-xs text-negative">{error.message}</p>}<div className="mt-2 divide-y divide-line">{data.map(item => { const symbol = item.nseSymbol || item.bseCode; const busy = (remove.isPending && remove.variables === symbol) || (pause.isPending && pause.variables?.symbol === symbol); return <div key={item.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{symbol}</p><p className="text-[11px] text-slate-500">Alerts {item.alertsPaused ? 'paused' : 'active'}</p></div><button disabled={busy} onClick={() => pause.mutate({ symbol, paused: !item.alertsPaused })} aria-label={`${item.alertsPaused ? 'Resume' : 'Pause'} alerts for ${symbol}`} className="rounded-lg border border-line p-2 text-slate-400 hover:text-white disabled:opacity-50">{item.alertsPaused ? <BellRing size={16}/> : <BellOff size={16}/>}</button><button disabled={busy} onClick={() => remove.mutate(symbol)} aria-label={`Remove ${symbol} from watchlist`} className="rounded-lg border border-line p-2 text-slate-400 hover:text-negative disabled:opacity-50"><Trash2 size={16}/></button></div>; })}</div></section>}</div>;
}
export function SignalPill({ label }) { const pos = label.includes('Positive') || label.includes('positive'), neg = label.includes('Negative') || label.includes('negative'); return <span className={`inline-flex gap-1.5 items-center text-[11px] rounded-full px-2 py-1 ${pos ? 'bg-positive/10 text-positive' : neg ? 'bg-negative/10 text-negative' : 'bg-slate-500/10 text-slate-400'}`}>{pos ? <TrendingUp size={12}/> : neg ? <TrendingDown size={12}/> : <Activity size={12}/>} {label}</span>; }
function NewsPanel({ data, onOpen }) { return <section className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Breaking timeline</h2><p className="text-xs text-slate-500 mt-1">Persisted, clustered and deduplicated</p></div><button onClick={onOpen} className="text-xs text-positive">Open explorer</button></div><div className="mt-5">{data.slice(0, 5).map((n) => <article key={n.id} className="relative pl-7 pb-6 last:pb-0 border-l border-line ml-2"><span className="absolute -left-1.5 top-1 h-3 w-3 rounded-full bg-positive border-[3px] border-panel"/><div className="flex flex-wrap gap-2 items-center text-[10px] text-slate-500"><span className="text-positive">{relativeTime(n.publishedAt)}</span><span>·</span><span>{n.sourceName}</span>{n.synthetic && <span className="border border-warning/30 text-warning rounded px-1.5">SYNTHETIC</span>}{n.official && <span className="border border-positive/30 text-positive rounded px-1.5">OFFICIAL</span>}</div><h3 className="text-sm font-medium mt-2">{n.title}</h3><div className="flex items-center gap-2 mt-3">{n.symbols?.map(symbol => <span key={symbol} className="text-[10px] rounded bg-cyan-400/10 text-cyan-300 px-2 py-1">{symbol}</span>)}{n.duplicateCount > 1 && <span className="text-[10px] text-slate-500">{n.duplicateCount} similar items</span>}</div></article>)}{!data.length && <p className="text-sm text-slate-500">No collected items yet. Start the ingestion worker to add policy-approved feed items.</p>}</div></section>; }
function Mood({ data }) { return <section className="surface rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-slate-500">Overall market mood</p><h2 className="text-lg font-semibold mt-2">{data?.label ?? 'Cautiously positive'}</h2></div><div className="h-14 w-14 rounded-full border-4 border-positive/20 border-t-positive grid place-items-center font-mono text-sm">{data?.score ?? 62}</div></div><p className="text-xs leading-5 text-slate-400 mt-4">{data?.explanation ?? 'Breadth is positive, while mixed global cues keep conviction moderate.'}</p><div className="mt-4 h-1.5 rounded-full bg-negative/30 overflow-hidden"><div className="h-full w-[62%] bg-gradient-to-r from-warning to-positive rounded-full"/></div><div className="flex justify-between text-[9px] text-slate-600 mt-1"><span>Risk-off</span><span>Balanced</span><span>Risk-on</span></div></section>; }
function SignalCard() { return <section className="surface rounded-2xl p-5 border-positive/20"><div className="flex items-center gap-2 text-positive"><Zap size={16}/><p className="text-[10px] uppercase tracking-[.16em] font-semibold">Signal spotlight</p></div><div className="flex items-center justify-between mt-4"><div><h3 className="font-semibold">RELIANCE</h3><SignalPill label="Positive setup"/></div><div className="text-right"><div className="font-mono text-lg">73%</div><div className="text-[10px] text-slate-500">confidence</div></div></div><div className="mt-4 border-t border-line pt-4"><h4 className="text-xs font-semibold">Why this signal?</h4><ul className="mt-2 space-y-2 text-xs text-slate-400"><li className="flex gap-2"><span className="text-positive">+</span>Synthetic capacity event rated potentially material.</li><li className="flex gap-2"><span className="text-positive">+</span>Mildly supportive delayed price context.</li><li className="flex gap-2"><span className="text-warning">!</span>No primary-source confirmation in demo mode.</li></ul></div><button className="w-full mt-4 rounded-lg border border-line py-2 text-xs text-slate-300 flex items-center justify-center gap-2"><FileText size={13}/>View evidence & invalidators</button><p className="mt-3 text-[9px] text-slate-600 leading-4">Informational research only. Not financial advice. Data is synthetic and delayed.</p></section>; }
function SourceHealth({ data }) { const h = data[0]; const healthy = h?.status === 'healthy'; return <section className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Source health</h2><span className={`text-[10px] flex gap-1.5 items-center ${healthy ? 'text-positive' : 'text-warning'}`}><span className={`h-1.5 w-1.5 rounded-full ${healthy ? 'bg-positive' : 'bg-warning'}`}/>{healthy ? 'Operational' : h ? 'Degraded' : 'Awaiting worker'}</span></div>{h ? <div className="mt-4 rounded-lg border border-line p-3 flex items-center gap-3"><div className="h-8 w-8 rounded-lg bg-positive/10 text-positive grid place-items-center"><ShieldCheck size={16}/></div><div className="min-w-0"><p className="text-xs truncate">{h.name}</p><p className="text-[10px] text-slate-500">Parser {h.parserVersion || 'not reported'} · {h.synthetic ? 'permitted fixture' : h.licence}</p></div></div> : <p className="mt-4 text-xs leading-5 text-slate-500">No source-health sample has been recorded. Start the ingestion worker.</p>}<button className="text-[11px] text-slate-500 mt-3 flex items-center">Open data-quality centre <ChevronRight size={13}/></button></section>; }
function SearchDialog({ onClose }) { const [q, setQ] = useState(''); const client = useQueryClient(); const results = useQuery({ queryKey: ['search', q], queryFn: () => api.search(q), enabled: q.length > 0 }); const add = useMutation({ mutationFn: (symbol) => api.addWatchlist(symbol), onSuccess: () => { client.invalidateQueries({ queryKey: ['watchlist'] }); onClose(); } }); return <div className="fixed inset-0 z-50 bg-black/65 backdrop-blur-sm p-4 sm:p-20" onMouseDown={e => e.target === e.currentTarget && onClose()}><div role="dialog" aria-modal="true" aria-label="Search stocks" className="surface max-w-2xl mx-auto rounded-2xl shadow-2xl overflow-hidden"><div className="flex items-center gap-3 p-4 border-b border-line"><Search size={20} className="text-positive"/><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Company, NSE symbol, BSE code or ISIN" className="bg-transparent flex-1 outline-none text-sm"/><button onClick={onClose} className="text-slate-500"><X size={18}/></button></div><div className="p-3 min-h-48 max-h-[60vh] overflow-y-auto scrollbar">{!q && <div className="py-14 text-center"><Search className="mx-auto text-slate-600"/><p className="text-sm text-slate-400 mt-3">Search the NSE/BSE security master</p><p className="text-xs text-slate-600 mt-1">Try RELIANCE, Infosys, 500180 or an ISIN</p></div>}{results.data?.data.map(s => <button disabled={add.isPending} onClick={() => add.mutate(s.nseSymbol || s.bseCode)} key={s.id} className="w-full flex items-center gap-3 rounded-xl p-3 hover:bg-white/[.04] text-left"><div className="h-9 w-9 rounded-lg bg-cyan-400/10 text-cyan-300 grid place-items-center text-xs font-semibold">{s.nseSymbol.slice(0, 2)}</div><div className="min-w-0"><div className="text-sm font-medium">{s.companyName}</div><div className="text-[11px] text-slate-500">NSE: {s.nseSymbol} · BSE: {s.bseCode} · {s.sector}</div></div><Plus size={16} className="ml-auto text-positive"/></button>)}{results.isFetching && <p className="text-center text-xs text-slate-500 py-8">Searching…</p>}{add.error && <p role="alert" className="m-3 p-3 rounded-lg bg-negative/10 text-negative text-xs">{add.error.message}</p>}</div><div className="border-t border-line px-4 py-3 text-[10px] text-slate-600 flex items-center justify-between"><span>Maximum 10 stocks per watchlist</span><span className="flex gap-1"><Pause size={11}/> Alerts can be paused</span></div></div></div>; }
export default App;
