import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ExternalLink, X } from 'lucide-react';
import { api } from './api';
import { relativeTime } from './news-utils';

const money = value => Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 });

export default function StockDetail({ symbol, onClose }) {
    const detail = useQuery({ queryKey: ['stock-detail', symbol], queryFn: () => api.stock(symbol), enabled: Boolean(symbol) });
    const news = useQuery({ queryKey: ['stock-news', symbol], queryFn: () => api.stockNews(symbol, { pageSize: 10 }), enabled: Boolean(symbol) });
    const item = detail.data?.data;
    const quote = item?.quote;
    return <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm p-3 sm:p-8" onMouseDown={event => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-label={`${symbol} market intelligence`} className="surface max-w-5xl mx-auto h-full rounded-2xl overflow-y-auto scrollbar p-5 sm:p-7">
        <div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-positive">Stock intelligence</p><h2 className="text-2xl font-semibold mt-2">{item?.security?.companyName ?? symbol}</h2><p className="text-xs text-slate-500 mt-1">NSE: {item?.security?.nseSymbol ?? symbol}{item?.security?.bseCode ? ` · BSE: ${item.security.bseCode}` : ''}{item?.security?.isin ? ` · ${item.security.isin}` : ''}</p></div><button onClick={onClose} aria-label="Close stock detail" className="text-slate-500 hover:text-white"><X size={20}/></button></div>
        {detail.isLoading && <p className="py-16 text-center text-sm text-slate-500 animate-pulse">Refreshing provider snapshot…</p>}
        {detail.error && <div role="alert" className="mt-5 rounded-xl bg-negative/10 p-4 text-sm text-negative">{detail.error.message}</div>}
        {item && <>
            <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-6"><Metric label="Last price" value={quote ? `₹${money(quote.lastPrice)}` : 'Unavailable'}/><Metric label="Day range" value={quote ? `₹${money(quote.dayLow)} – ₹${money(quote.dayHigh)}` : 'Unavailable'}/><Metric label="52-week range" value={quote ? `₹${money(quote.yearLow)} – ₹${money(quote.yearHigh)}` : 'Unavailable'}/><Metric label="Volume" value={quote ? money(quote.volume) : 'Unavailable'}/></section>
            {quote && <div className={`mt-3 rounded-xl border p-4 text-xs ${quote.synthetic ? 'border-warning/25 bg-warning/[.04]' : 'border-line bg-white/[.02]'}`}><p><span className="text-slate-500">Source:</span> {quote.source} · {quote.isDelayed ? 'delayed' : 'provider-defined freshness'} {quote.synthetic ? '· SYNTHETIC' : ''}</p><p className="text-slate-500 mt-1">Market as of {new Date(quote.asOf).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST · retrieved {new Date(quote.retrievedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST</p></div>}
            <div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="rounded-2xl border border-line p-5"><h3 className="font-semibold">Fundamentals</h3><p className="text-xs text-slate-500 mt-1">Period, unit and accounting basis are kept with every value.</p><div className="mt-4 divide-y divide-line">{item.fundamentals?.metrics?.map(metric => <div key={metric.key} className="flex justify-between gap-4 py-3"><div><p className="text-sm">{metric.label}</p><p className="text-[10px] text-slate-500">{metric.period} · {metric.basis}</p></div><p className="font-mono text-sm">{money(metric.value)} {metric.unit}</p></div>)}{!item.fundamentals?.metrics?.length && <p className="text-sm text-slate-500 py-6">No provider fundamentals available.</p>}</div></section><section className="rounded-2xl border border-line p-5"><h3 className="font-semibold">Risk flags</h3><div className="mt-4 space-y-3">{item.riskFlags?.map(flag => <div key={flag.code} className="rounded-xl bg-white/[.025] p-4 flex gap-3"><AlertTriangle size={16} className={flag.severity === 'high' ? 'text-negative' : 'text-warning'}/><div><p className="text-sm">{flag.title}</p><p className="text-xs leading-5 text-slate-500 mt-1">{flag.explanation}</p></div></div>)}{!item.riskFlags?.length && <p className="text-sm text-slate-500 py-6">No deterministic risk flag triggered.</p>}</div></section></div>
            <section className="rounded-2xl border border-line p-5 mt-5"><h3 className="font-semibold">Sector peers</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{item.peers?.map(peer => <div key={peer.symbol} className="rounded-xl bg-white/[.025] p-4"><p className="text-sm font-medium">{peer.symbol}</p><p className="text-[10px] text-slate-500 truncate">{peer.companyName}</p><p className="font-mono mt-3">₹{money(peer.lastPrice)}</p><p className={`text-xs mt-1 ${peer.changePercent >= 0 ? 'text-positive' : 'text-negative'}`}>{Number(peer.changePercent).toFixed(2)}% · P/E {money(peer.peRatio)}</p></div>)}{!item.peers?.length && <p className="text-sm text-slate-500">No same-sector peer snapshots available.</p>}</div></section>
            <section className="rounded-2xl border border-line p-5 mt-5"><h3 className="font-semibold">Recent stock news</h3><p className="text-xs text-slate-500 mt-1">Up to 10 clustered, deduplicated articles from policy-approved configured sources.</p><div className="grid lg:grid-cols-2 gap-3 mt-4">{(news.data?.data ?? []).slice(0, 10).map(article => <a key={article.id} href={article.url} target="_blank" rel="noreferrer" className="rounded-xl bg-white/[.025] p-4 hover:bg-white/[.04]"><div className="flex items-center gap-2 text-[10px] text-slate-500"><span className="text-positive">{relativeTime(article.publishedAt)}</span><span>·</span><span>{article.sourceName}</span><ExternalLink size={11}/></div><p className="text-sm mt-2">{article.title}</p></a>)}{!news.isLoading && !news.data?.data?.length && <p className="text-sm text-slate-500 lg:col-span-2 py-6">No policy-approved article has been linked to {symbol} yet.</p>}</div></section>
            <p className="text-[10px] text-slate-600 mt-6">Prices and ratios are informational provider snapshots. Signals and risk flags are not financial advice.</p>
        </>}
    </section></div>;
}

function Metric({ label, value }) { return <div className="rounded-xl border border-line bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="font-mono mt-2">{value}</p></div>; }
